In [10]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

from google.colab import files

In [11]:
# Upload file
uploaded = files.upload()

df = pd.read_csv("listings.csv.gz")
df.head()

Saving listings.csv.gz to listings.csv (2).gz

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,90676,https://www.airbnb.com/rooms/90676,20250926165842,2025-09-26,city scrape,Short North - Italianate Cottage,Just steps from High Street and all the action...,The Short North Italianate Cottage is located ...,https://a0.muscache.com/pictures/950e43cd-53f3...,483306,...,4.87,4.92,4.76,2022-2475,f,3,3,0,0,5.11
1,591101,https://www.airbnb.com/rooms/591101,20250926165842,2025-09-26,city scrape,Bellows Studio Loft Apartment,Famous American artist George Bellows home wit...,A historic neighborhood of beautiful victorian...,https://a0.muscache.com/pictures/32b28442-ddf3...,2889677,...,4.91,4.89,4.89,2019-1230,f,1,0,1,0,2.14
2,927867,https://www.airbnb.com/rooms/927867,20250926165842,2025-09-26,city scrape,Full Private Room at the Hostel,The Wayfaring Buckeye Hostel is a social place...,We are located in the vibrant University Distr...,https://a0.muscache.com/pictures/08033ebe-286c...,4965048,...,4.85,4.65,4.68,2019-1314,f,5,1,4,0,0.56
3,1183297,https://www.airbnb.com/rooms/1183297,20250926165842,2025-09-26,city scrape,Hannah's Haus**Prime location in German Village**,Hannah's Haus in German Village is a stunning ...,German Village is a historic neighborhood just...,https://a0.muscache.com/pictures/miso/Hosting-...,6473080,...,4.98,4.78,4.82,NaN,f,3,3,0,0,1.80
4,1217678,https://www.airbnb.com/rooms/1217678,20250926165842,2025-09-26,city scrape,Comfortable rooms in Clintonville 1,"A cozy, warm, inviting place to stay in the he...",The house is on a quiet and residential street...,https://a0.muscache.com/pictures/airflow/Hosti...,5707733,...,4.99,4.97,4.94,2025-2824,f,2,0,2,0,1.90

In [12]:
# Kristal's RF attempt

from sklearn.ensemble import RandomForestRegressor
from scipy import stats

# Data Cleaning
df_rf = df.copy()
df_rf['price'] = df_rf['price'].replace(r'[\$,]', '', regex=True).astype(float)
df_rf = df_rf[df_rf['price'] > 0]
df_rf['bathrooms'] = df_rf['bathrooms_text'].str.extract(r'(\d+\.?\d*)').astype(float)

#  Feature Engineering
df_rf['log_price']        = np.log1p(df_rf['price'])
df_rf['price_per_person'] = df_rf['price'] / df_rf['accommodates']
df_rf['review_density']   = df_rf['number_of_reviews'] / (df_rf['minimum_nights'] + 1)

#  Additional Features
df_rf['host_is_superhost'] = (df_rf['host_is_superhost'] == 't').astype(int)
df_rf['instant_bookable']  = (df_rf['instant_bookable'] == 't').astype(int)

#  Outlier Removal (3 standard dev on log_price)
before = len(df_rf)
df_rf = df_rf[np.abs(stats.zscore(df_rf['log_price'])) < 3]
after = len(df_rf)
print(f"Rows removed as outliers: {before - after}")

# Features
features_rf = [
    'accommodates', 'bathrooms', 'bedrooms', 'beds',
    'minimum_nights', 'number_of_reviews', 'review_scores_rating',
    'room_type', 'neighbourhood_cleansed',
    'price_per_person', 'review_density',
    'host_is_superhost', 'instant_bookable',
]

df_rf_model = df_rf[features_rf + ['log_price']].dropna()
df_rf_model = pd.get_dummies(
    df_rf_model,
    columns=['room_type', 'neighbourhood_cleansed'],
    drop_first=True
)

X_rf = df_rf_model.drop(columns=['log_price'])
y_rf = df_rf_model['log_price']

X_rf_train, X_rf_test, y_rf_train, y_rf_test = train_test_split(
    X_rf, y_rf, test_size=0.2, random_state=42
)

print(f"Training rows:      {X_rf_train.shape[0]}")
print(f"Test rows:          {X_rf_test.shape[0]}")
print(f"Number of features: {X_rf_train.shape[1]}")

#  Hyperparameters
rf_params = {
    "n_estimators":      300,
    "max_depth":         20,
    "min_samples_split": 5,
    "min_samples_leaf":  2,
    "random_state":      42,
    "n_jobs":            -1
}

# Train
rf_model = RandomForestRegressor(**rf_params)
rf_model.fit(X_rf_train, y_rf_train)
y_rf_pred = rf_model.predict(X_rf_test)

# Metrics
mae_rf  = mean_absolute_error(y_rf_test, y_rf_pred)
rmse_rf = np.sqrt(mean_squared_error(y_rf_test, y_rf_pred))
r2_rf   = r2_score(y_rf_test, y_rf_pred)

# Feature importance
feature_importance = pd.DataFrame({
  'Feature':    X_rf.columns,
  'Importance': rf_model.feature_importances_
  }).sort_values(by='Importance', ascending=False)

print("\nTop 10 Most Important Features:")
print(feature_importance.head(10).to_string(index=False))
print(mae_rf)
print(rmse_rf)
print(r2_rf)

Rows removed as outliers: 20
Training rows:      1902
Test rows:          476
Number of features: 38

Top 10 Most Important Features:
               Feature  Importance
          accommodates    0.580575
      price_per_person    0.388967
              bedrooms    0.023403
room_type_Private room    0.003401
             bathrooms    0.000944
                  beds    0.000666
        review_density    0.000438
  review_scores_rating    0.000436
     number_of_reviews    0.000401
        minimum_nights    0.000255
0.014018938337177952
0.04290743706661594
0.9944942814475853

In [13]:
GITHUB_USERNAME = "mcclantr"
GITHUB_TOKEN    = "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"
REPO_NAME       = "Project-BANA7075"

!git clone https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git /content/{REPO_NAME}

print("✓ Repo cloned!")
!ls /content/Project-BANA7075/reports/

fatal: destination path '/content/Project-BANA7075' already exists and is not an empty directory.
✓ Repo cloned!
experiment_log.csv

In [14]:
csv_path = "/content/Project-BANA7075/reports/experiment_log.csv"
df_log = pd.read_csv(csv_path)

print("Current log:")
display(df_log)

Current log:

,run_name,date,author,dataset_version,features,preprocessing,model,hyperparameters,rmse,mae,r^2,notes
0,baseline_lr_01,4/5/2026,Thomas,v1,accommodates+bedrooms+beds+minimum_nights+numb...,price cleaned + dropna,LinearRegression,default,2274.745528,317.524388,0.006622,Very weak baseline; likely affected by outliers
1,baseline_lr_02_improved,4/5/2026,Thomas,v1,accommodates+bathrooms+bedrooms+beds+minimum_n...,price cleaned + outliers removed (price <= 100...,LinearRegression,default,0.328504,0.268087,0.666998,Improved linear regression with outlier remova...
2,rf_01,4/6/2026,Thomas,v1,accommodates+bathrooms+bedrooms+beds+minimum_n...,price cleaned + outliers removed (price <= 100...,RandomForestRegressor,"n_estimators=200,max_depth=15,min_samples_spli...",0.302918,0.234433,0.716850,Random Forest benchmark against improved linea...
3,linear_regression_03,2026-04-18,Kristal,v3,"accommodates, bathrooms, bedrooms, beds, minim...",price cleaned + outliers removed (3 sd of log ...,Linear Regression,none,0.214000,0.160500,0.863000,Feature engineering: added price_per_person an...

In [20]:

new_row = {
    "run_name":        "rf_kristal_feature_engineering",
    "date":            "2026-04-18",
    "author":          "Kristal",
    "dataset_version": "v5",
    "features":        "accommodates, bathrooms, bedrooms, beds, minimum_nights, number_of_reviews, review_scores_rating, room_type, neighbourhood_cleansed, price_per_person, review_density, host_is_superhost, instant_bookable",
    "preprocessing":   "log_price + zscore outliers + engineered features + superhost + instant_bookable",
    "model":           "Random Forest",
    "hyperparameters": "n_estimators=300, max_depth=20, min_samples_split=5, min_samples_leaf=2, random_state=42",
    "rmse":            round(rmse_rf, 4),
    "mae":             round(mae_rf, 4),
    "r^2":             round(r2_rf, 4),
    "notes":           "Kristal RF: engineered features + superhost + instant_bookable + zscore outlier removal"
}

if new_row["run_name"] in df_log["run_name"].values:
    print("⚠️ This run is already in the log — skipping")
else:
    df_log = pd.concat([df_log, pd.DataFrame([new_row])], ignore_index=True)
    print(f"✓ Added {new_row['run_name']}")

print(f"Total rows in log: {len(df_log)}")
display(df_log)

⚠️ This run is already in the log — skipping
Total rows in log: 5

,run_name,date,author,dataset_version,features,preprocessing,model,hyperparameters,rmse,mae,r^2,notes
0,baseline_lr_01,4/5/2026,Thomas,v1,accommodates+bedrooms+beds+minimum_nights+numb...,price cleaned + dropna,LinearRegression,default,2274.745528,317.524388,0.006622,Very weak baseline; likely affected by outliers
1,baseline_lr_02_improved,4/5/2026,Thomas,v1,accommodates+bathrooms+bedrooms+beds+minimum_n...,price cleaned + outliers removed (price <= 100...,LinearRegression,default,0.328504,0.268087,0.666998,Improved linear regression with outlier remova...
2,rf_01,4/6/2026,Thomas,v1,accommodates+bathrooms+bedrooms+beds+minimum_n...,price cleaned + outliers removed (price <= 100...,RandomForestRegressor,"n_estimators=200,max_depth=15,min_samples_spli...",0.302918,0.234433,0.716850,Random Forest benchmark against improved linea...
3,linear_regression_03,2026-04-18,Kristal,v3,"accommodates, bathrooms, bedrooms, beds, minim...",price cleaned + outliers removed (3 sd of log ...,Linear Regression,none,0.214000,0.160500,0.863000,Feature engineering: added price_per_person an...
4,rf_kristal_feature_engineering,2026-04-18,Kristal,v6,"accommodates, bathrooms, bedrooms, beds, minim...",log_price + zscore outliers + engineered featu...,Random Forest,"n_estimators=300, max_depth=20, min_samples_sp...",0.042900,0.014000,0.994500,Kristal RF: engineered features + superhost + ...

In [21]:
# Fix version numbers
df_log.loc[0, 'dataset_version'] = 'v1'
df_log.loc[1, 'dataset_version'] = 'v2'
df_log.loc[2, 'dataset_version'] = 'v3'
df_log.loc[3, 'dataset_version'] = 'v4'
df_log.loc[4, 'dataset_version'] = 'v5'

print("✓ Versions updated")
display(df_log)

✓ Versions updated

,run_name,date,author,dataset_version,features,preprocessing,model,hyperparameters,rmse,mae,r^2,notes
0,baseline_lr_01,4/5/2026,Thomas,v1,accommodates+bedrooms+beds+minimum_nights+numb...,price cleaned + dropna,LinearRegression,default,2274.745528,317.524388,0.006622,Very weak baseline; likely affected by outliers
1,baseline_lr_02_improved,4/5/2026,Thomas,v2,accommodates+bathrooms+bedrooms+beds+minimum_n...,price cleaned + outliers removed (price <= 100...,LinearRegression,default,0.328504,0.268087,0.666998,Improved linear regression with outlier remova...
2,rf_01,4/6/2026,Thomas,v3,accommodates+bathrooms+bedrooms+beds+minimum_n...,price cleaned + outliers removed (price <= 100...,RandomForestRegressor,"n_estimators=200,max_depth=15,min_samples_spli...",0.302918,0.234433,0.716850,Random Forest benchmark against improved linea...
3,linear_regression_03,2026-04-18,Kristal,v4,"accommodates, bathrooms, bedrooms, beds, minim...",price cleaned + outliers removed (3 sd of log ...,Linear Regression,none,0.214000,0.160500,0.863000,Feature engineering: added price_per_person an...
4,rf_kristal_feature_engineering,2026-04-18,Kristal,v5,"accommodates, bathrooms, bedrooms, beds, minim...",log_price + zscore outliers + engineered featu...,Random Forest,"n_estimators=300, max_depth=20, min_samples_sp...",0.042900,0.014000,0.994500,Kristal RF: engineered features + superhost + ...

In [22]:
df_log.to_csv(csv_path, index=False)

!git config --global user.email "abelka@mail.uc.edu"
!git config --global user.name "mcclantr"

%cd /content/Project-BANA7075
!git add reports/experiment_log.csv
!git commit -m "Fix dataset version numbers in experiment log"
!git push
print("✓ Pushed to GitHub!")

/content/Project-BANA7075
[main 3cdd18f] Fix dataset version numbers in experiment log
 1 file changed, 4 insertions(+), 3 deletions(-)
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 664 bytes | 664.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/mcclantr/Project-BANA7075.git
   5e3b29c..3cdd18f  main -> main
✓ Pushed to GitHub!